const CONSTANTS = {};

CONSTANTS.ERROR_MESSAGE = {};

CONSTANTS.ERROR_MESSAGE.TRAKS_GET =
  "Request to retrieve Traks failed:";

CONSTANTS.ENDPOINT = {};
CONSTANTS.DEFAULT_COLOR = "#00ff00";
CONSTANTS.JAKKER_URL = "http://10.0.0.20:9000/jakk";
CONSTANTS.GRAPHQL_URL = "http://10.0.0.20:4000/graphql";
CONSTANTS.WEBSOCKET_GRAPHQL_URL = "ws://10.0.0.20:4000/ws/graphql";

export default CONSTANTS;
